
workspace:
  ckpts_folder: 'ckpts'
  logs_folder: 'logs'
  epoch_prefix: 'e'
  ckpts_extension: '.pt'
  step_key: 'step'

# add your configurations below
base:
  model.input_dim: 10
  model.hidden_dim: 10
  model.output_dim: 10
  optim.lr: 1e-3

base/test1:
  model.hidden_dim: 20

base/test2: